#pragma kernel CSMain

RWTexture2D<float4> Texture;
Texture2D<float4> Source;

bool InCarpet(uint x, uint y) {
	while (x > 0 || y > 0) {
		if (x % 3 == 1 && y % 3 == 1) {
			return true;
		};
		x /= 3;
		y /= 3;
	}
	return false;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID) {

	Texture[id.xy] = Source[id.xy];
	
	if (InCarpet(id.x, id.y)) {
		Texture[id.xy] = float4(0.8, 0.2, 0.2, 1);
	}
}